sudo: false
language: java
notifications:
  email: false
jdk:
- oraclejdk8
before_install: wget https://gist.githubusercontent.com/Doridian/01cb63301fe4d022f533bd221e227970/raw/0771d2c50808b295abfbabe266be7368c3273974/settings.xml
  -O settings.bin
script: mvn deploy -DaltDeploymentRepository=deployment-repo-id::default::https://maven.doridian.net/repository/maven-snapshots/
  --settings settings.bin
env:
  global:
  - secure: hfDRKIdBKuJf2hX7KjHAytXQV2m7/A6W6g8g7HTQdr9bVNmseapH78ZqOoB5Ga/gT6eh8VpNrYlusaBdI7i+rqeKI3y5CMreBOP3bkkTeivJ5+StHuF2RYEbG91QwPST6vj+aq4TqpsKVDscIyJruS+VPTTf0K9fEzYP47+nT5Q=
  - secure: bZbTqJgHvpZCj1DEgwrn6Q9dKf2lfVjMFqnKbM4l+T0sidn8hFl1mnHxUZz5FTvz68fVwNA+ylNOEzrXuacywivWnX6eyFKYrbMHeNvKB4hepTvQohLFf1ZN+BWxIuRhjJoH2xaAY9ke/ZbZwpIeHCgZq2WYN0RbjSzNhJvlEVQ=
